[project]
name = "python-tools-sl"
version = "0.1.0"
description = "Petits utilitaires Python (d√©corateurs, helpers, etc.)"
authors = [{name="Serge"}]
dependencies = ["pytest"]

[tool.setuptools.packages.find]
where = ["."]
include = ["python_tools_sl*"]
